// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjzfubfdgtcxiwfztkky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqemZ1YmZkZ3RjeGl3Znp0a2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNDQ0NDQsImV4cCI6MjA1NTgyMDQ0NH0._yp9HmmhN6l1DPwWcsKa5cjnPrcY9OCf9xt7cBjMq4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);